 name: MPO624
 channels:
   - conda-forge
   - damianavila82
   - ioam
 dependencies:
   - python=3
   - jupyter
   - jupyterlab
   - rise
   - numpy
   - matplotlib
   - jsanimation
   - scikit-learn
   - eofs
   - cartopy
   - seaborn
   - netcdf4
   - owslib
   - metpy
   - pint
   - shapely<=1.5.17
   - siphon
   - xarray
   - holoviews
   - geoviews
   - iris
   - pip
   - ffmpeg
   - pytest
   - ipywidgets
   - pip:
     - python-awips
     - mpldatacursor
     - drilsdown
